# Generated by Django 5.0.4 on 2024-07-15 13:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=250)),
                ('kid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='parents.kid')),
            ],
        ),
    ]
